# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xci
# IP: The module: 'hello_word_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xci
# IP: The module: 'hello_word_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
