# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hello_word/hello_word.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word || ORIG_REF_NAME==hello_word}]

# IP: bd/hello_word/ip/hello_word_microblaze_0_0/hello_word_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_microblaze_0_0 || ORIG_REF_NAME==hello_word_microblaze_0_0}]

# IP: bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_mdm_1_0 || ORIG_REF_NAME==hello_word_mdm_1_0}]

# IP: bd/hello_word/ip/hello_word_clk_wiz_1_0/hello_word_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_clk_wiz_1_0 || ORIG_REF_NAME==hello_word_clk_wiz_1_0}]

# IP: bd/hello_word/ip/hello_word_rst_clk_wiz_1_100M_0/hello_word_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==hello_word_rst_clk_wiz_1_100M_0}]

# IP: bd/hello_word/ip/hello_word_axi_uartlite_0_0/hello_word_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_axi_uartlite_0_0 || ORIG_REF_NAME==hello_word_axi_uartlite_0_0}]

# IP: bd/hello_word/ip/hello_word_microblaze_0_axi_periph_0/hello_word_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hello_word_microblaze_0_axi_periph_0}]

# IP: bd/hello_word/ip/hello_word_mig_7series_0_0/hello_word_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_mig_7series_0_0 || ORIG_REF_NAME==hello_word_mig_7series_0_0}]

# IP: bd/hello_word/ip/hello_word_axi_smc_0/hello_word_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_axi_smc_0 || ORIG_REF_NAME==hello_word_axi_smc_0}]

# IP: bd/hello_word/ip/hello_word_rst_mig_7series_0_81M_0/hello_word_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==hello_word_rst_mig_7series_0_81M_0}]

# IP: bd/hello_word/ip/hello_word_dlmb_v10_0/hello_word_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_dlmb_v10_0 || ORIG_REF_NAME==hello_word_dlmb_v10_0}]

# IP: bd/hello_word/ip/hello_word_ilmb_v10_0/hello_word_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_ilmb_v10_0 || ORIG_REF_NAME==hello_word_ilmb_v10_0}]

# IP: bd/hello_word/ip/hello_word_dlmb_bram_if_cntlr_0/hello_word_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hello_word_dlmb_bram_if_cntlr_0}]

# IP: bd/hello_word/ip/hello_word_ilmb_bram_if_cntlr_0/hello_word_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hello_word_ilmb_bram_if_cntlr_0}]

# IP: bd/hello_word/ip/hello_word_lmb_bram_0/hello_word_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_word_lmb_bram_0 || ORIG_REF_NAME==hello_word_lmb_bram_0}]

# XDC: bd/hello_word/hello_word_ooc.xdc
