# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.cache/wt [current_project]
set_property parent.project_path C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/hdl/hello_word_wrapper.v
add_files C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/hello_word.bd
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_microblaze_0_0/hello_word_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_microblaze_0_0/hello_word_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_microblaze_0_0/hello_word_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mdm_1_0/hello_word_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_clk_wiz_1_0/hello_word_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_clk_wiz_1_0/hello_word_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_clk_wiz_1_0/hello_word_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_clk_wiz_1_100M_0/hello_word_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_clk_wiz_1_100M_0/hello_word_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_clk_wiz_1_100M_0/hello_word_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_uartlite_0_0/hello_word_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_uartlite_0_0/hello_word_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_uartlite_0_0/hello_word_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mig_7series_0_0/hello_word_mig_7series_0_0/user_design/constraints/hello_word_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mig_7series_0_0/hello_word_mig_7series_0_0/user_design/constraints/hello_word_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_mig_7series_0_0/hello_word_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_12/bd_957c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_21/bd_957c_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_24/bd_957c_m00s2a_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_25/bd_957c_m00arn_0/bd_957c_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_25/bd_957c_m00arn_0/bd_957c_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_25/bd_957c_m00arn_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_26/bd_957c_m00rn_0/bd_957c_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_26/bd_957c_m00rn_0/bd_957c_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_26/bd_957c_m00rn_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_27/bd_957c_m00awn_0/bd_957c_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_27/bd_957c_m00awn_0/bd_957c_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_27/bd_957c_m00awn_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_28/bd_957c_m00wn_0/bd_957c_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_28/bd_957c_m00wn_0/bd_957c_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_28/bd_957c_m00wn_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_29/bd_957c_m00bn_0/bd_957c_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_29/bd_957c_m00bn_0/bd_957c_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_29/bd_957c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_22/bd_957c_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_23/bd_957c_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_13/bd_957c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_14/bd_957c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_15/bd_957c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_16/bd_957c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_17/bd_957c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_4/bd_957c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_5/bd_957c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_6/bd_957c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_7/bd_957c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_8/bd_957c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_1/bd_957c_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_1/bd_957c_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_2/bd_957c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_2/bd_957c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_3/bd_957c_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/bd_0/ip/ip_3/bd_957c_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_mig_7series_0_81M_0/hello_word_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_mig_7series_0_81M_0/hello_word_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_rst_mig_7series_0_81M_0/hello_word_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_dlmb_v10_0/hello_word_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_dlmb_v10_0/hello_word_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_ilmb_v10_0/hello_word_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_ilmb_v10_0/hello_word_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_dlmb_bram_if_cntlr_0/hello_word_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_ilmb_bram_if_cntlr_0/hello_word_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_lmb_bram_0/hello_word_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/hello_word_ooc.xdc]
set_property is_locked true [get_files C:/Users/iShift/Documents/VivadoProjects/hello_word/hello_word.srcs/sources_1/bd/hello_word/hello_word.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top hello_word_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef hello_word_wrapper.dcp

catch { report_utilization -file hello_word_wrapper_utilization_synth.rpt -pb hello_word_wrapper_utilization_synth.pb }
